- name: Deploying Istio 
  hosts: localhost
  connection: local
  gather_facts: False
  become_user: root
  become: true
  tasks:
  
    - name: Download the Istio installation file
      get_url:
        url: https://github.com/istio/istio/releases/download/1.16.1/istio-1.16.1-linux-amd64.tar.gz
        dest: /tmp
        
        
    - name: Unarchive the installation file
      unarchive:
        src: /tmp/istio-1.16.1-linux-amd64.tar.gz
        dest: /tmp
        
        
    - name: Move Istioctl binary to local
      shell: mv istioctl /usr/local/bin
      args:
        chdir: /tmp/istio-1.16.1/bin
        
        
    - name: Clone minishift add-on repo
      git:
        repo: 'https://github.com/minishift/minishift-addons'
        dest: /tmp/minishift-addons
        clone: yes
        update: yes
        
      
    - name: Check if istio add on has been installed 
      stat:
        path: /root/.minishift/profiles/servicemesh/addons/istio
      register: output
        
        
    - name: Install istio addon
      shell: minishift addon install istio
      args:
        chdir: /tmp/minishift-addons/add-ons
      when: not output.stat.exists
      
    
    - name: Deploy istio resources
      shell: "{{ item }}"
      loop:
        - minishift addon enable istio
        - minishift addon apply istio
        
        
    - name: Check if istio-system namespace is created 
      shell: oc get ns istio-system
      register: output
      until: output.rc == 0
      retries: 50
      delay: 5
      
        
    - name: Check if istio resources in istio namespace are ready
      k8s_info:
        kind: Pod
        namespace: istio-system
      register: istio_checker
      until: istio_checker.resources | selectattr('metadata.name','match','kiali')
      retries: 90
      delay: 10
        
        
    - name: Enable admission webhook in minishift
      shell: "{{ item }}" 
      loop:
        - minishift addons install --defaults
        - minishift addons enable admissions-webhook
        - minishift addons apply admissions-webhook
        
        
    - name: Give some time for the admission webhook to be fully enabled
      wait_for:
        timeout: 30
        
        
    - name: Create our "devops" namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: devops
        state: present
      register: ns_output
       
       
    - name: Label our devops namespace to allow for istio sidecar injection
      k8s:
        state: patched
        kind: Namespace
        name: devops
        definition:
          metadata:
            labels:
              istio-injection: enabled
              
              
    - name: Port-forward Kialia service
      shell: oc port-forward svc/kiali 7000:20001
      async: 1800
      poll: 0
      
      
    - name: Port-forward Grafana service
      shell: oc port-forward svc/grafana 7001:3000
      async: 1800
      poll: 0
      
      
    - name: JAEGER | list all the istio pods
      k8s_info:
        kind: Pod
        namespace: istio-system
      register: pod_list
      
      
    - name: JAEGER | Fetch the name of the jaeger UI pod
      debug:
        msg: "Name of jaeger pod: {{ pod_list.resources[13].metadata.name }}" 
        
        
    - name: Port-forward Jaeger pod
      shell: "oc port-forward pods/{{ pod_list.resources[13].metadata.name }} 7002:16686"
      async: 1800
      poll: 0
 
