- name: Setting Up Minishift
  hosts: localhost
  connection: local
  gather_facts: False
  become_user: root
  become: true
  tasks:
  
  - name: Set variable(s)
    set_fact:
      VER: 1.34.3
  
  - name: Install libvirt and qemu-kvm on your system
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    loop:
      - qemu-kvm
      - libvirt-daemon
      - libvirt-daemon-system
        
        
  - name: Check to see if KVM is already installed on the host
    stat:
      path: /usr/local/bin/docker-machine-driver-kvm
    register: KVM_STATUS
  
  
  - name: Install the KVM driver binary
    get_url:
      url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-ubuntu16.04
      dest: /usr/local/bin/docker-machine-driver-kvm
    register: download_kvm
      
      
  - name: Give executable permission for kvm binary
    file:
      path: /usr/local/bin/docker-machine-driver-kvm
      state: file
      mode: a+x
      
      
  - name: Start the libvirtd service
    systemd:
      name: libvirtd
      enabled: true 
      state: started
      
      
  - name: Start the default libvirt network
    shell: net-start default
    ignore_errors: true
    
    
  - name: Check to see if minishift is already installed on the host
    stat: 
      path: /usr/local/bin/minishift-{{ VER }}-linux-amd64/minishift
    environment:
      VER: 1.34.3
    register: MINISHIFT_STATUS
    
    
  - name: download minishift tar file
    get_url:
      url: "https://github.com/minishift/minishift/releases/download/v{{ VER }}/minishift-{{ VER }}-linux-amd64.tgz"
      dest: /tmp
    environment:
      VER: 1.34.3
      
      
  - name: unarchive the downloaded file
    unarchive:
      src: "/tmp/minishift-{{ VER }}-linux-amd64.tgz"
      dest: /tmp
      
      
  - name: Add Minishift binary to /usr/local/bin directory
    shell: mv minishift-{{ VER }}-linux-amd64/minishift /usr/local/bin
    args:
      chdir: /tmp
      
      
  - name: Attempt to start the minishift cluster
    block:
    
      - name: Configure minishift installation
        shell: "{{ item }}"
        loop: 
          - minishift profile set servicemesh
          - minishift config set memory 8GB
          - minishift config set cpus 4
          - minishift config set image-caching true
          - minishift config set openshift-version v3.11.0
          - minishift addon enable admin-user
          - minishift addon enable anyuid
      
      
      - name: Start minishift
        shell: minishift start
        register: minishift_start
      
      
    rescue:
      - name: Delete the corrupted cluster and clear its cache
        shell: minishift delete --force --clear-cache
        
        
      - name: Configure minishift installation
        shell: "{{ item }}"
        loop: 
          - minishift config set memory 8GB
          - minishift config set cpus 4
          - minishift config set image-caching true
          - minishift config set openshift-version v3.11.0
          - minishift addon enable admin-user
          - minishift addon enable anyuid
        
        
      - name: Configure minishift installation
        script: ./minishift_config.sh
        
        
      - name: Start the cluster again
        shell: minishift start
        
      
  - name: Copy OC binary
    copy:
      src: /root/.minishift/cache/oc/v3.11.0/linux/oc
      dest: /usr/local/bin
      mode: a+x
    
    
  - name: Login to the cluster as the admin user
    shell: oc login -u admin -p admin
   
