apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  db_name: "example-database"
  {{- with .Values.DB_CRED }}
  db_server: {{ .host | default "https://my-db.com" | quote }}
  db_username: {{ .username | upper | quote }}
  db_password: {{ .password | b64enc }}
  ChartName: {{ $.Release.Name }}
  {{- end }}
  users: |-
    {{- range .Values.USERS }}
    - {{ . | quote }}
    {{- end }}
