apiVersion: apps/v1
kind: Deployment
{{ template "demo-helm.deploy-front" }}
  template: 
    metadata:
    {{- include "demo-helm.annotations" . | indent 6 }}
      labels:
        app: front-deploy
    spec:
      containers:
      - image: {{ .Values.front_image }}
        name: front-deploy       
        ports:
        - containerPort: 7000
        
---

apiVersion: apps/v1
kind: Deployment
{{ template "demo-helm.deploy-mid" }}
  template: 
    metadata:
      {{- include "demo-helm.annotations" . | indent 6 }}
      labels:
        app: mid-deploy
    spec:
      containers:
      - image: {{ .Values.mid_image }}
        name: mid-deploy      
        ports:
        - containerPort: 8000
        
---

apiVersion: apps/v1
kind: Deployment
{{ template "demo-helm.deploy-back-v1" }}
  template: 
    metadata:
      {{- include "demo-helm.annotations" . | indent 6 }}
      labels:
        app: back-deploy
        version: original
    spec:
      containers:
      - image: {{ .Values.back_image_1 }}
        name: back-deploy      
        ports:
        - containerPort: 9000
        
---

apiVersion: apps/v1
kind: Deployment
{{ template "demo-helm.deploy-back-v2" }}
  template: 
    metadata:
      {{- include "demo-helm.annotations" . | indent 6 }}
      labels:
        app: back-deploy
        version: canary
    spec:
      containers:
      - image: {{ .Values.back_image_2 }}
        name: back-deploy      
        ports:
        - containerPort: 9000
        
---

{{- range $key, $val := .Values.SERVICES }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
spec:
  selector:
    app: {{ $val.app }}
  ports:
    - name: http
      port: {{ $val.port }}
      targetPort: {{ $val.targetport }}

---
{{- end }}
